language: node_js

node_js:
  - lts/*

os: linux

dist: focal

cache: yarn

script:
  - travis_retry yarn test

before_deploy:
  - yarn build

deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_token: $NPM_TOKEN
    skip_cleanup: true
    on:
      tags: true
